sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in travis-deployer-sincere-hybrid-224616-c147a8e8461e.json.enc -out travis-deployer-sincere-hybrid-224616-c147a8e8461e.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-deployer-sincere-hybrid-224616-c147a8e8461e.json
  - gcloud config set project sincere-hybrid-224616
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sharmaarun/ci_cd_test -f ./moleculer-test/Dockerfile.dev ./moleculer-test

script:
  - docker run sharmaarun/ci_cd_test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master