apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: sharmaarun/ci_cd_tut
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: mongodb-cluster-ip-service
            - name: MONGO_PORT
              value: '27017'