sudo : required
services:
  - docker

before_install:
  - docker build -t sharmaarun/ci_cd_test -f ./Dockerfile.dev .

script:
  - docker run sharmaarun/ci_cd_test npm test

after_success:
  - docker build -t sharmaarun/ci_cd_tut:latest .
  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push the image
  - docker push sharmaarun/ci_cd_tut:latest
